### ISSUE TITLE
Support other color orders like NeoPixel

### ISSUE THREAD

**Issue by RedAnon** [adafruit/Adafruit_CircuitPython_DotStar#15]
APA Electronic has a new [13-bit version of the APA-102](http://neon-world.com/en/product_detail.php?cid=59&id=114) LEDs which have a lower refresh rate (approximately 700MHz) but smoother colours.
As far as I can tell there is currently no way of controlling these chips. And it would be extremely awesome if we could control them.

**Comment by tannewt** [comment]
I'm not sure these will need any changes. A forum user (may be @RedAnon ) is going to test next week and get back to me.

https://forums.adafruit.com/viewtopic.php?f=60&t=135009

**Comment by tannewt** [comment]
Mimic the NeoPixel library.

https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/blob/master/neopixel.py#L39

**Comment by RedAnon** [comment]
Thanks. I've already forwarded this to our company's developer and he will try to implement it.

**Comment by mcscope** [comment]
Mine! Working on this @ pycon sprints

**Comment by RedAnon** [comment]
What's your ETA @mcscope? I can't promise you we won't be faster. :P

**Comment by mcscope** [comment]
@RedAnon I'm working on it now @ the pycon sprints. 
 I am wondering if your initial message (about 13 bits) was referring to the 5 bit brightness value per-pixel? I noticed this library doesn't support using it, but it's part of the spec. I'm opening another issue for that because this one is about color order now.

**Comment by mcscope** [comment]
other issue about global brightness bit: https://github.com/adafruit/Adafruit_CircuitPython_DotStar/issues/16

**Comment by RedAnon** [comment]
@mcscope Yes it was. AFAIK the driver right now simply sends a fixed value but people from APA USA told me that this should only work for their 8-bit LEDs (even tho it plainly works for the 13-bit ones as well as I've demonstrated on the Adafruit forums).
The plan right now for us is to tackle that (#16) issue as well and our in-house developer is investigating it as we speak. It's just that we've wanted to start with something easier but it seems you've already solved that. :)

**Comment by mcscope** [comment]
PR: https://github.com/adafruit/Adafruit_CircuitPython_DotStar/pull/18

**Comment by RedAnon** [comment]
@mcscope 
[APA-102-2020 (8-Bit version, same page for both the 6 and the 8 pad chips) - Genuine part](http://neon-world.com/en/product_detail.php?cid=61&id=172)
[APA-102-2020-8192-8 (13-Bit version, 8 pad chips) - Genuine part](http://neon-world.com/en/product_detail.php?cid=61&id=244)
[Forum thread where I've tested the 13-Bit strips with 8-Bit code.](https://forums.adafruit.com/viewtopic.php?f=60&t=135009&sid=73efde9dfd46997719371fdecaa397b7)

And yes, as far as I know the 5-Bit value added to the 8-Bit colour plays an important role in fully utilizing the 13-Bit chips. Problem is the data from the manufacturer are a bit sketchy. For example they were adamant that sending 8-Bit code to 13-Bit LEDs would never ever work but it does...

**Comment by tannewt** [comment]
Fixed by #18
