### ISSUE TITLE
Dotstar updates are slow

### ISSUE THREAD

**Issue by rhooper** [adafruit/Adafruit_CircuitPython_DotStar#25]
The dotstar library could benefit from a CircuitPython helper to offload computationally expensive setitem work to. 
See adafruit/circuitpython#884

**Comment by rhooper** [comment]
I have done some experimental work on this for Neopixels, see adafruit/circuitpython#884 and https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/issues/27

**Comment by kattni** [comment]
@tannewt This needs to be updated to work with pixelbuf as well. There is some work here: https://github.com/rhooper/Adafruit_CircuitPython_DotStar/blob/pixelbuf/adafruit_dotstar.py

**Comment by tannewt** [comment]
@dunkmann00 want to take a stab at it?

**Comment by dunkmann00** [comment]
Sure! I don't have any dotstars to test it though. But I think it should be straight forward enough, especially since there is already some work done on it.

**Comment by tannewt** [comment]
@dunkmann00 That'd be awesome. We can find someone with DotStars to verify the code. Thanks!

**Comment by kattni** [comment]
We did it!
