### ISSUE TITLE
_ds_writebytes() clock rises before data is written

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_DotStar#34]
@schelmo has noted that clock rises before data bit is written on the bitbanging implementation in `_ds_writebytes()` in https://github.com/adafruit/Adafruit_CircuitPython_WS2801/pull/4

That code is the same and probably originated from here. Check origins of this code and find other occurrences. Forum post to see if anyone is using non hardware assisted pins, i.e. why has this only just been noticed.

(This could be a direct translation of some flawed C code which worked because timing was far tighter??)

**Comment by schelmo** [comment]
i tested this with dotstars now
(trinket m0, data -> d0, clock -> d1)
no weird colors like for the ws2801
if i rise the clock pin after the data bit is written (like in pull request adafruit/Adafruit_CircuitPython_WS2801#4),
everything still works like expected

**Comment by ladyada** [comment]
@schelmo wanna submit a PR here too? :)

**Comment by kevinjwalters** [comment]
The [APA102C datasheet](https://cdn-shop.adafruit.com/product-files/2343/APA102C.pdf) from [DotStar Addressable 5050 RGB LED](https://www.adafruit.com/product/2343) does make it look like these are edge triggered on the rising edge for reading data in:

![adafruit-dotstar-shiji-apa102c-datasheet-dataclock-snippet](https://user-images.githubusercontent.com/6851309/57695552-7426d100-7646-11e9-964c-8aa836026b00.PNG)


Curious that it works either way with CircuitPython, though.

**Comment by kevinjwalters** [comment]
The C/C++ code in https://github.com/adafruit/Adafruit_DotStar/blob/master/Adafruit_DotStar.cpp has three implementations - the two non-hardware assisted ones in that code all do clocking _after_ the data is set.

**Comment by kattni** [comment]
Fixed by #35
