### ISSUE TITLE
Change more led dots directly

### ISSUE THREAD

**Issue by miloit** [adafruit/Adafruit_CircuitPython_DotStar#54]
Hello, how can I change a range of led dots at the same time?

**Comment by kattni** [comment]
@miloit You would use a slice to change a range of LEDs. For example, you would use the following code to light up the first five DotStar LEDs. This line of code assumes you setup the DotStars as `dotstars`.
```
dotstars[0:5] = (255, 255, 0) * 5
```
Slicing works the same in CircuitPython as it does in Python, however, you need to include the `* N` (where N is the size of the slice) after the RGB color tuple so it generates the color for all of the members of the slice. 

Hopefully this helps. I'm going to close this issue. For future reference, you'll get better assistance with questions like this on the [Adafruit forums](https://forums.adafruit.com/viewforum.php?f=60) or the [Adafruit Discord](https://adafru.it/discord). If you need further assistance, please choose one of those two options to pursue your question. Thanks!
