### ISSUE TITLE
Arrange a random color to more dots directly

### ISSUE THREAD

**Issue by miloit** [adafruit/Adafruit_CircuitPython_DotStar#55]
Hello,
I try to define a random color and apply it to 5 dots directly here is my code

`r = random.randint(0, 255)
 g = random.randint(0, 255)
 b = random.randint(0, 255)
 self.strip[0:5] = (r,g,b) * 5
 self.strip.show()
`

But it is always blue.

What is the issue?

**Comment by tannewt** [comment]
Please ask on [the forum](https://forums.adafruit.com/viewforum.php?f=60) or [Discord](https://adafru.it/discord) for technical support. Issues are for tracking issues that require code changes in a library.
