### ISSUE TITLE
Not Fast enough

### ISSUE THREAD

**Issue by 0U55AMA** [adafruit/Adafruit_CircuitPython_DotStar#57]
Think you for your great effort ,
 I have a problem i would be grateful if you could help me to solve it , I am **building a POV Display** project , My motor is turning **25 spin per second** (1500 RPM) , there is **64 LEDs** of HD107S (same to **Dotstar** but have much higher addressing frequency "30 Mhz" ) , the problem is **the speed of scanning is not fast enough**, therefore **I see lines and not dots**  i barely show the flower , is there any way to speed up scanning time ? like change the frequency  for example ....
![229133030_362877652178721_2239607621087714214_n](https://user-images.githubusercontent.com/88337590/127936857-03baecaf-a216-4a24-bd11-4916e73f6f52.jpg)
 

Testing the Dotstar library give better result than Apa102-pi library  , but it still far from objective ,  i didn't find how to change frequency  , and it seems that the library get the value and send it at same time , therefor there is much time loss ,I would be grateful if you can help to find way to set higher frequency , in order to have the less refresh time possible . 
![Dotstar VS Apa102-pi lib](https://user-images.githubusercontent.com/88337590/128004933-6f42cd88-f04a-41e7-b2c2-990aa8d54cac.png)

**Apa102-pi** loop : 

while 1:
if GPIO.input(15) == GPIO.HIGH: 
  strip.set_pixel_rgb(30, 0x00000F) 
  strip.show() 
  strip.set_pixel_rgb(30, 0x000000) 
  strip.show() 
 
 
**Dotstar** loop : 

while 1: 
 if GPIO.input(15) == GPIO.HIGH: 
  pixels[30] = (10, 0, 0)
  pixels[30] = (0, 0, 0)

**Comment by tannewt** [comment]
Please ask about this on the support forum: https://forums.adafruit.com/viewforum.php?f=60

We'll want to know details about what you are running the code on as well.
