### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by wilwet** [adafruit/Adafruit_CircuitPython_DotStar#61]
DeprecationWarning: The symbol module is deprecated and will be removed in future versions of Python from symbol import testlist_star_expr.

In version 2.2.5

**Comment by tekktrik** [comment]
Can you provide the line number for the import referenced here?  I can't seem to find it.

**Comment by tekktrik** [comment]
Can you also provide the code you ran when this occurred?  I'm not sure it's coming from this library, so that information would help track it down.

**Comment by wilwet** [comment]
Sorry, my bad it was a lingering import "from symbol import testlist_star_expr" in a example code.
