### ISSUE TITLE
example `dotstar_image_pov.py` imports PIL

### ISSUE THREAD

**Issue by s-light** [adafruit/Adafruit_CircuitPython_DotStar#64]
https://github.com/adafruit/Adafruit_CircuitPython_DotStar/blob/main/examples/dotstar_image_pov.py

is this example meant for linux?
i thought its a normal *uC* example..

it uses `from PIL import Image`
and i did not find any information how to use PIL from CircuitPython...

**Comment by Neradoc** [comment]
Yep, the 2 image examples are for desktop python.
It would be interesting to write a version using `adafruit_imageload` or `OnDiskBitmap`.

**Comment by s-light** [comment]
thanks!

maybe add a note in the file comment?

i currently know of these two *manual* image reading & converting versions:
- [Clue Light Paintstick](https://learn.adafruit.com/clue-light-paintstick/code-with-circuitpython) [extracted code](https://github.com/s-light/cp_magic_painter/blob/main/src/bmp2led.py)
- [CircuitPython Painter](https://learn.adafruit.com/circuitpython-painter) [extracted code](https://github.com/s-light/cp_magic_painter/blob/main/src/povpainter.py#L348)

and i also thought of using [`adafruit_imageload`](https://docs.circuitpython.org/projects/imageload/en/latest/) and [`OnDiskBitmap`](https://docs.circuitpython.org/en/latest/shared-bindings/displayio/index.html#displayio.OnDiskBitmap)

if i implement it in my project i try to strip it down and create a additional example here :-)
